apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
spec:
  serviceName: {{ .Values.postgres.name }}
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.db.password }}
            - name: PGDATA
              value: {{ .Values.postgres.db.pgData }}
          ports:
            - containerPort: {{ .Values.postgres.db.port }}
              name: {{ .Values.postgres.name }}
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: {{ .Values.postgres.db.pgData }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.volume.size }}
