apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    app: {{ .Values.app.name }}
    type: local
data:
  PG_HOST: {{ .Values.postgres.name }}
  PG_DATABASE: {{ .Values.postgres.db.database }}
  PG_PORT: "{{ .Values.postgres.db.port }}"
  PG_USER: {{ .Values.postgres.db.user }}
  PG_PASSWORD: {{ .Values.postgres.db.password }}
