name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Perform authentication to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish application image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/basic-python-app:latest
          platforms: linux/amd64,linux/arm64/v8
      - name: Build and publish PostgreSQL image
        uses: docker/build-push-action@v6
        with:
          file: ./db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/postgres:13.15
          platforms: linux/amd64,linux/arm64/v8
